version: '3.8'
services:
  app:
    build: .
    container_name: yamama-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    command: 
      sh -c "
        until nc -z yamama-db 5432; do
        echo '⏳ Waiting for Postgres...';
        sleep 1;
        done &&
      yarn migrate &&
      yarn dev "


  postgres:
    image: postgres:16
    container_name: yamama-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yamamadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
